spring.application.name=12SpringWebMvcEx-1
#Port number details
server.port=9191
#View Resolver details
# --- prefix must starts with / and ends with /
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix = .jsp
